### ISSUE TITLE
Check that all links in docs are valid

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#444]
Once #443 is done, we will have lots of links that may get stale.

Add a test to the tests und `ui/` that checks for links in all documentation markdown files and verifies that there's a document served at the link destination.

**Comment by aryabharat** [comment]
Hi, @djmitche Is this issue is resolved or not?
If not then I would like to do it, can you give m a bit more idea about it.

**Comment by djmitche** [comment]
Hi!  No, it's not resolved.

This will be a bit tricky.  We want to write a test case that checks all links in the documentation.  There are a few tests already in https://github.com/taskcluster/taskcluster/tree/master/ui/test but they are very limited unit tests that just run a function and check the result.

If i was working on this, I might start by getting those existing tests to run for me, then work on a test that just loads every documentation file in the UI.  That probably requires "crawling" the site, and you can find an example of that [here](https://github.com/taskcluster/taskcluster/pull/699) although I'm sure that's the best approach.  Once the crawler is crawling, the next step is to find every link within the content of the documentation and check that its target exists.

An alternative approach would be to write a test that looks at the `.md` files in the repository under `ui/docs` directly, extracting the links and checking that those links point to a valid location.  Exactly what constitutes a "valid location" might be a bit difficult to determine.

So, this is a bit of a difficult project since it has some big "unknown" bits in it.  But if you're interested in trying to figure those things out, you're welcome to!

**Comment by aryabharat** [comment]
Thanks for the details.
I think the second approach of checking the .md is better, but still, we have to figure it out exactly what constitutes a "valid location" might be a bit difficult to determine. I can give it a try, 
I will do some work n then get back to you.

**Comment by aryabharat** [comment]
We have to check that the link points to a local file or external file or both?

**Comment by djmitche** [comment]
Only internal links need to be checked -- external links can be ignored.

**Comment by aryabharat** [comment]
And by checking we mean to see if the file is present or not that's it?

**Comment by djmitche** [comment]
Correct!

**Comment by aryabharat** [comment]
Hi, I was writing the test to check the valid links n all, but I got a npm package 
https://github.com/remarkjs/remark-validate-links
This package fulfills all our requirements, below are the files found missing by the remark
[missing.txt](https://github.com/taskcluster/taskcluster/files/3269195/missing.txt)

Now do let m know that does it suitable for out projects or should I proceed with the test script?

**Comment by aryabharat** [comment]
Hey, have you seen this???

**Comment by djmitche** [comment]
That package looks great -- let's use it!

However, it seems that it only validates internal links to hashes:

```
This [exists](#alpha).
```
and not links between files:
```
This is [not checked](readme.md#bravo).
```
so it doesn't quite do the whole job here.

**Comment by aryabharat** [comment]
Sorry! I will you pls explain it more. If it doesn't complete the work I will try something else.

**Comment by djmitche** [comment]
It won't detect broken links from one document to another -- only broken links *within* a document.

**Comment by aryabharat** [comment]
I have gone for your approch

> to write a test that looks at the .md files in the repository under ui/docs directly, extracting the links and checking that those links point to a valid location


So i have used **markdown-link-extractor** to extract link and filer out all the External URLs.
```
const fs = require('fs');
function isValidURL(string) {
    var res = string.match(/(http(s)?:\/\/.)/);
    if (res == null)
      return false;
    else
      return true;
  };
var markdownLinkExtractor = require('markdown-link-extractor');
var markdown = fs.readFileSync('README.md').toString();
var links = markdownLinkExtractor(markdown);

links.forEach(function (link) {
    if(!isValidURL(link))
        {
            console.log(link);
            fs.access(link, fs.F_OK, (err) => {
                if (err) {
                  console.error(err)
                  return
                }
                console.log(link + "  FOUNDED!!\n");
                //file exists
              })
        }
});
```
I still need to work on it as it does give true for a link with a # and its case sensitive 
eg:(src/component/DateDistance#README.md)

**Just wanted to know that the approch is working corect or not?**

**Comment by djmitche** [comment]
Yes, it seems like you're on the right track!

**Comment by aryabharat** [comment]
Hey! I tried it for ui/readme its working, do suggest me any chnages if you want
```
const fs = require('fs');
function isValidURL(string) {
  var res = string.match(/(http(s)?:\/\/.)/);
  if (res == null)
    return false;
  else
    return true;
};
var markdownLinkExtractor = require('markdown-link-extractor');

var markdown = fs.readFileSync('README.md').toString();

var links = markdownLinkExtractor(markdown);
links.forEach(function (link) {
  if (!isValidURL(link)) {
   link  =  link.replace('#', '/');
   link = link.replace('readme','README.md')
    fs.access(link, fs.F_OK, (err) => {
      if (err) {
        console.error('\x1b[33m%s\x1b[0m',err.message);
        return;
      }
    })
  }
});
```

**Comment by aryabharat** [comment]
SIr?

**Comment by djmitche** [comment]
It's looking good so far.  There will probably be several types of links, not all of them pointing to markdown files.  I'd suggest abstracting the is-this-link-ok check a little bit, so that we can add a few different definitions of "valid link" and allow a link that matches at least one such definition.

Also, we will want to put this in the form of a Mocha test suite, so rather than using `console.error`, it should cause the test case to fail.  Ideally, the exception from the failure will include all of the invalid links, not just the first one it finds.  For example, when this fails:
https://github.com/taskcluster/taskcluster/blob/6b6af4ae590801db2bc3f635b6772c3c3feca742/test/meta_test.js#L33-L35
the user gets a message with all of the missing or extra items.

**Comment by aryabharat** [comment]
Sure!  I will do it in mocha, and I am sure this code checks the link when it is pointing to different not particularly an md file.

**Comment by subhamskm** [comment]
Hey @aryabharat, are you still working on this issue?

**Comment by aryabharat** [comment]
Hi @subhamskm! yes, I am working on it.

**Comment by helfi92** [comment]
👋 @aryabharat How is it going? :-)

**Comment by aryabharat** [comment]
HI, @helfi92 I am stuck with some issue in mocha, as I just started it.
I got free from some of my work just now, ill be back on it now.
and if you have a different approach then pls let m know.

**Comment by aryabharat** [comment]
HI, @helfi92 I am stuck with some issue in mocha, as I just started it.
I got free from some of my work just now, ill be back on it now.
and if you have a different approach then pls let m know.

**Comment by carpecodeum** [comment]
can i take this if this issue is not being worked on?

**Comment by djmitche** [comment]
@aryabharat is it OK if @carpecodeum takes this issue?

**Comment by aryabharat** [comment]
Sure @djmitche

**Comment by carpecodeum** [comment]
Ok thank you i will start working on it.

**Comment by vishakhanihore** [comment]
@djmitche Please assign me this.

**Comment by djmitche** [comment]
@vishakhanihore go ahead and have a look.  @carpecodeum if you are still actively working on this, let us know ASAP?

As you can see from the comments here, this is a tricky one!

**Comment by bhushan-borole** [comment]
Hello @djmitche 
I would love to start working on this.

**Comment by djmitche** [comment]
This is quite difficult, it seems -- probably more difficult than the reward of finishing it.
